version: "3"
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - default
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data

  kbn:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    depends_on:
      - es
    ports:
      - 5601:5601
    networks:
      - default

  ls:
    image: docker.elastic.co/logstash/logstash:7.7.0
    container_name: logstash
    depends_on:
      - es
      - kbn
    networks:
      - default
    volumes:
      - ./pipeline/:/usr/share/logstash/pipeline/

networks:
  default:
    external:
      name: zookeeper_main

volumes:
  esdata1:
    driver: local
  pipeline:
    driver: local